### ISSUE TITLE
environment-QuTiP.yml : ResolvePackageNotFound when creating conda environment

### ISSUE THREAD

**Issue by pybeaudouin** [qsharp-community/chp-sim#1] opened 2020-07-17 02:49 UTC
Hello, I get the following error when trying to create a conda environment:

```
$ conda env create --file environment-QuTiP.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - numpy==1.18.4=py38h72c728b_0
  - kiwisolver==1.2.0=py38heaebd3c_0
  - matplotlib-base==3.2.1=py38h1626042_0
  - openssl==1.1.1g=he774522_0
  - zlib==1.2.11=h2fa13f4_1006
  - sqlite==3.30.1=hfa6e2cd_0
  - vs2015_runtime==14.16.27012=h30e32a0_2
  - jpeg==9c=hfa6e2cd_1001
  - mistune==0.8.4=py38h9de7a3e_1001
  - zeromq==4.3.2=h6538335_2
  - msys2-conda-epoch==20160418=1
  - m2w64-gcc-libs==5.3.0=7
  - python==3.8.2=h5fd99cc_7_cpython
  - icc_rt==2019.0.0=h0cc432a_1
  - pyrsistent==0.16.0=py38h9de7a3e_0
  - pyzmq==19.0.1=py38h77b9d75_0
  - scipy==1.3.2=py38h582fac2_0
  - markupsafe==1.1.1=py38h9de7a3e_1
  - vc==14.1=h869be7e_1
  - icu==64.2=he025d50_1
  - freetype==2.10.1=ha9979f8_0
  - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
  - libpng==1.6.37=hfe6a214_1
  - pyqt==5.12.3=py38h7ae7562_3
  - tornado==6.0.4=py38hfa6e2cd_0
  - qutip==4.5.0=py38h79cbd7a_0
  - m2w64-gcc-libs-core==5.3.0=7
  - ipykernel==5.2.1=py38h5ca1d4c_0
  - cython==0.29.17=py38h7ae7562_0
  - libsodium==1.0.17=h2fa13f4_0
  - winpty==0.4.3=4
  - wincertstore==0.2=py38_1003
  - libclang==9.0.1=default_hf44288c_0
  - pywinpty==0.5.7=py38_0
  - m2w64-gcc-libgfortran==5.3.0=6
  - m2w64-gmp==6.1.0=2
  - pywin32==227=py38hfa6e2cd_0
  - qt==5.12.5=h7ef1ec2_0


$ conda --version
conda 4.8.3
```

Using miniconda and macOS 10.15

**Comment by RolfHuisman** [comment] 2020-07-17 13:58
Hmm.. Most of those dependencies look to be for Windows anyway. Will take some time to split out what dependencies keep it multiplatform. But before we do that, @crazy4pi314  since this is a helper tool, do people need it in daily use ?

**Comment by RolfHuisman** [comment] 2020-07-18 09:34
As confirmed in #2 by @pybeaudouin should be fixed.

**Closed as completed by RolfHuisman** 2020-07-18 09:34 UTC
